
spring:
  application:
    name: springoauth2 demo
  http:
    encoding:
      force: true
      charset: utf-8
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/springbootoauth2v2?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      新版本的mysql driver
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      pool-prepared-statements: true
  redis:
    host: localhost
    port: 6379

authentication:
  jwtTokenSecret: nolanWin
  tokenExpiredMs: 5184000
